version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(actions): "
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:13"
      timezone: Europe/London
    rebase-strategy: disabled
    cooldown:
      default-days: 3
      exclude:
        - "quotidian-ennui/workflows-olio/*"
        - "quotidian-ennui/actions-olio/*"
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"
          - "quotidian-ennui/actions-olio/*"
  - package-ecosystem: docker
    open-pull-requests-limit: 10
    directories:
      - "liberica-alpine"
      - "msopenjdk"
      - "temurin"
      - "zulu-alpine"
    rebase-strategy: disabled
    cooldown:
      default-days: 3
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:23"
      timezone: "Europe/London"
    allow:
      - dependency-type: all
    commit-message:
      prefix: "deps(docker-image): "
