name: docker-tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Get git tag
      id: tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
    - name: docker buildx eclipse-temurin
      run: |
        echo Building lewinc/activemq:${{ steps.tag.outputs.tag }}
        docker buildx build . --platform linux/amd64,linux/arm64/v8,linux/arm/v7 \
            -t lewinc/activemq:${{ steps.tag.outputs.tag }} \
            -f debian/Dockerfile --push
    - name: docker buildx zulu-alpine
      # no zulu-alpine for arm64 (only jdk17 has it)
      run: |
        echo Building lewinc/activemq:${{ steps.tag.outputs.tag }}-zulu-alpine
        docker buildx build . --platform linux/amd64 \
            -t lewinc/activemq:${{ steps.tag.outputs.tag }}-zulu-alpine \
            -f debian/Dockerfile --push
