name: docker-build-latest

on:
  push:
    branches: main
    paths-ignore:
      - "README.md"

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}