name: docker build on pr
run-name: Build & Test PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

# A push via dependabot basically means that the github actions
# have been upgraded; that doesn't mean we need to
# Push a new image.
jobs:
  build:
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: false
      target_branch: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
