name: docker build on pr
run-name: Build & Test PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.client_payload.detail.pull_request || github.ref }}
  cancel-in-progress: true

# A push via dependabot basically means that the github actions
# have been upgraded; just make sure that the docker build works
# but don't push a new image.
jobs:
  docker_build:
    uses: ./.github/workflows/docker-build-image.yml
    permissions:
      contents: write
      packages: write
      pull-requests: write
      statuses: write
    with:
      registry_push: false
      target_branch: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  actions_merge:
    name: Dependabot Merge (action changes)
    needs:
      - docker_build
    if: |
      github.event.client_payload.base.actor == 'dependabot[bot]'
    uses: quotidian-ennui/workflows-olio/.github/workflows/action-dependabot-merge.yml@eff82979a276acf5fdad410c646fc2527dbc3331 # v2.2.4
    with:
      client_id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
