name: docker build on pr
run-name: Build & Test PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

# A push via dependabot basically means that the github actions
# have been upgraded; just make sure that the docker build works
# but don't push a new image.
jobs:
  docker_build:
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: false
      target_branch: ${{ github.event.client_payload.base.ref }}
      sha: ${{ github.event.client_payload.base.sha }}
      pull_request: ${{ github.event.client_payload.detail.pull_request }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  actions_merge:
    runs-on: ubuntu-latest
    name: Dependabot Merge (action changes)
    needs:
      - docker_build
    steps:
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.client_payload.base.ref }}
      - name: "Create Token"
        uses: actions/create-github-app-token@e8e39f73bb84fdf315a015fa3104f314c0a258b4 # v1.8.1
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@main
        with:
          token: ${{ steps.app-token.outputs.token }}
